### PR TITLE
fix build

### PR DESCRIPTION
**Pull request by benpicco**
The last commit broke the build.
Fix it.

### CODE REVIEW

**Comment by AaronLiddiment** [comment]
Were you born that obnoxious or did it take years of learning?
If you put the same effort into programming then you wouldn't need other peoples classes.

**Comment by benpicco** [comment]
Well I don't care if your project builds or not, probably better if it doesn't as it will lead people to the [more advanced fork](https://github.com/Jorgen-VikingGod/LEDMatrix).

**Comment by AaronLiddiment** [comment]
I see you just want to keep proving my point for me!

Why a more advanced fork needs to add a wasteful DrawPixel() command is strange as my class already had this with 'led(x, y) = CRGB(0,0,0)'.
The aim of my class was to keep code size as small as possible whilst being flexible which it achieved, I never intended it for multi matrix. The forked version does this well but at the expense of code size.

It's people like you who are not so talented that feed off the open source community whilst being obnoxious to people you don't even know. Manners don't cost anything.

**Comment by benpicco** [comment]
I'm still puzzled as to how I wronged you for fixing a missed semicolon.
At least I have my editor under control so it doesn't rewrite the entire file for a single line change.

**Pull request closed without merging**
